### ISSUE TITLE
关于局域网服务

### ISSUE THREAD

**Issue by firstuanl** [vctfence/scrapbee_backend#1]
你好

想在局域网内使用scapbee backend服务，使用0.0.0.0设置没有成功。看webscrapbook似呼有这个功能。

1.7.3在ubuntu X64下启动不了，还好有备份1.7.1

scapbee backend旧版文件网络上是否有备份。

谢谢

**Comment by vctfence** [comment]
1.7.3 支持手工启动和监听 0.0.0.0， 如果启动不了请手工编译， 见 readme.

**Comment by firstuanl** [comment]
好，试试

**Comment by firstuanl** [comment]
编译1。7。3有连接成功，但不知怎的不显示内容。
自动连接也不显示内容。
-----

[info] version = 2.1.4
[info] browser = Firefox 74.0
[info] platform = Linux x86-64
[info] connect web server: address = http://127.0.0.1:9901/
[info] connect web server: connected, version = 1.7.3
[info] show rdf list

----

[info] version = 2.1.5
[info] browser = Firefox 82.0.2
[info] platform = Win x86-64
[info] connect web server: address = http://192.168.2.219:9901/
[info] connect web server: connected, version = 1.7.3
[info] show rdf list
